# Generated by Django 2.2.16 on 2022-03-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_auto_20220306_2313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_recipe",
                to="recipe.Ingredient",
            ),
        ),
    ]
