# Generated by Django 2.2.16 on 2022-03-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_auto_20220312_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
