# Generated by Django 2.2.16 on 2022-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
